:-style_check(-discontiguous).
person_status("person.anisa", not_home).
domain("person.anisa", "person").
entity_type("person.anisa", single).
person_status("person.tablet", home).
domain("person.tablet", "person").
entity_type("person.tablet", single).
person_status("person.jakob", not_home).
domain("person.jakob", "person").
entity_type("person.jakob", single).
group("light.table_lamp", "group.living_room").
group("light.sofa_lamp", "group.living_room").
group("sensor.motion_sensor_light_level", "group.living_room").
entity_type("group.living_room", group).
temperature_sensor_status("sensor.living_room_temperature_a_13", high).
domain("sensor.living_room_temperature_a_13", "temperature").
entity_type("sensor.living_room_temperature_a_13", single).
actuator("switch.unknown_zwave_1", off).
domain("switch.unknown_zwave_1", "switch").
actuator_type("switch.unknown_zwave_1", switch).
entity_type("switch.unknown_zwave_1", single).
actuator("light.all_lights", off).
domain("light.all_lights", "light").
actuator_type("light.all_lights", light).
entity_type("light.all_lights", group).
light_sensor_status("sensor.living_room_light_a_14", low).
domain("sensor.living_room_light_a_14", "light").
entity_type("sensor.living_room_light_a_14", single).
actuator("switch.living_room_plug_1_18", on).
domain("switch.living_room_plug_1_18", "switch").
actuator_type("switch.living_room_plug_1_18", switch).
entity_type("switch.living_room_plug_1_18", single).
actuator("light.living_room_tv_plug_22", on).
domain("light.living_room_tv_plug_22", "light").
actuator_type("light.living_room_tv_plug_22", light).
entity_type("light.living_room_tv_plug_22", single).
actuator("switch.tv_switch", on).
domain("switch.tv_switch", "switch").
actuator_type("switch.tv_switch", switch).
entity_type("switch.tv_switch", single).
actuator("switch.window_switch", off).
domain("switch.window_switch", "switch").
actuator_type("switch.window_switch", window).
entity_type("switch.window_switch", single).
actuator("light.test_light_1", off).
domain("light.test_light_1", "light").
actuator_type("light.test_light_1", light).
entity_type("light.test_light_1", single).
actuator("light.test_light_2", off).
domain("light.test_light_2", "light").
actuator_type("light.test_light_2", light).
entity_type("light.test_light_2", single).
light_sensor_status("sensor.sm_t725_light_sensor", low).
domain("sensor.sm_t725_light_sensor", "light").
entity_type("sensor.sm_t725_light_sensor", single).
temperature_sensor_status("sensor.sm_t725_battery_temperature", high).
domain("sensor.sm_t725_battery_temperature", "temperature").
entity_type("sensor.sm_t725_battery_temperature", single).
temperature_sensor_status("sensor.living_room_door_magnet_temp_25", high).
domain("sensor.living_room_door_magnet_temp_25", "temperature").
entity_type("sensor.living_room_door_magnet_temp_25", single).
actuator("light.table_lamp", off).
domain("light.table_lamp", "light").
actuator_type("light.table_lamp", light).
entity_type("light.table_lamp", single).
actuator("light.sofa_lamp", off).
domain("light.sofa_lamp", "light").
actuator_type("light.sofa_lamp", light).
entity_type("light.sofa_lamp", single).
temperature_sensor_status("sensor.corner_temperature", medium).
domain("sensor.corner_temperature", "temperature").
entity_type("sensor.corner_temperature", single).
light_sensor_status("sensor.corner_light_level", low).
domain("sensor.corner_light_level", "light").
entity_type("sensor.corner_light_level", single).
temperature_sensor_status("sensor.door_temperature", medium).
domain("sensor.door_temperature", "temperature").
entity_type("sensor.door_temperature", single).
light_sensor_status("sensor.door_light_level", low).
domain("sensor.door_light_level", "light").
entity_type("sensor.door_light_level", single).
temperature_sensor_status("sensor.motion_sensor_temperature", medium).
domain("sensor.motion_sensor_temperature", "temperature").
entity_type("sensor.motion_sensor_temperature", single).
light_sensor_status("sensor.motion_sensor_light_level", medium).
domain("sensor.motion_sensor_light_level", "light").
entity_type("sensor.motion_sensor_light_level", single).
temperature_sensor_status("sensor.window_sensor_temperature", medium).
domain("sensor.window_sensor_temperature", "temperature").
entity_type("sensor.window_sensor_temperature", single).
light_sensor_status("sensor.window_sensor_light_level", low).
domain("sensor.window_sensor_light_level", "light").
entity_type("sensor.window_sensor_light_level", single).
actuator("light.livingroom", off).
domain("light.livingroom", "light").
actuator_type("light.livingroom", light).
entity_type("light.livingroom", group).
temperature_sensor_status("sensor.netatmo_smart_home_temperature", high).
domain("sensor.netatmo_smart_home_temperature", "temperature").
entity_type("sensor.netatmo_smart_home_temperature", single).

write_output(Response):-
	open('automation_results/2022_05_03_14_57_14.txt', append, Out),
	write(Out, Response),
	close(Out).

